INSERT INTO flashcards (user_id, front, back) VALUES
(1, 'Qual é a capital do Acre?',                'A capital do Acre é Rio Branco.'),
(1, 'Qual é a capital de Alagoas?',             'A capital de Alagoas é Maceió.'),
(1, 'Qual é a capital do Amapá?',               'A capital do Amapá é Macapá.'),
(1, 'Qual é a capital do Amazonas?',            'A capital do Amazonas é Manaus.'),
(1, 'Qual é a capital da Bahia?',               'A capital da Bahia é Salvador.'),
(1, 'Qual é a capital do Ceará?',               'A capital do Ceará é Fortaleza.'),
(1, 'Qual é a capital do Distrito Federal?',    'A capital do Distrito Federal é Brasília.'),
(1, 'Qual é a capital do Espírito Santo?',      'A capital do Espírito Santo é Vitória.'),
(1, 'Qual é a capital de Goiás?',               'A capital de Goiás é Goiânia.'),
(1, 'Qual é a capital do Maranhão?',            'A capital do Maranhão é São Luís.'),
(1, 'Qual é a capital do Mato Grosso?',         'A capital do Mato Grosso é Cuiabá.'),
(1, 'Qual é a capital do Mato Grosso do Sul?',  'A capital do Mato Grosso do Sul é Campo Grande.'),
(1, 'Qual é a capital de Minas Gerais?',        'A capital de Minas Gerais é Belo Horizonte.'),
(1, 'Qual é a capital do Pará?',                'A capital do Pará é Belém.'),
(1, 'Qual é a capital da Paraíba?',             'A capital da Paraíba é João Pessoa.'),
(1, 'Qual é a capital do Paraná?',              'A capital do Paraná é Curitiba.'),
(1, 'Qual é a capital de Pernambuco?',          'A capital de Pernambuco é Recife.'),
(1, 'Qual é a capital do Piauí?',               'A capital do Piauí é Teresina.'),
(1, 'Qual é a capital do Rio de Janeiro?',      'A capital do Rio de Janeiro é Rio de Janeiro.'),
(1, 'Qual é a capital do Rio Grande do Norte?', 'A capital do Rio Grande do Norte é Natal.'),
(1, 'Qual é a capital do Rio Grande do Sul?',   'A capital do Rio Grande do Sul é Porto Alegre.'),
(1, 'Qual é a capital de Rondônia?',            'A capital de Rondônia é Porto Velho.'),
(1, 'Qual é a capital da Roraima?',             'A capital da Roraima é Boa Vista.'),
(1, 'Qual é a capital de Santa Catarina?',      'A capital de Santa Catarina é Florianópolis.'),
(1, 'Qual é a capital de São Paulo?',           'A capital de São Paulo é São Paulo.'),
(1, 'Qual é a capital de Sergipe?',             'A capital de Sergipe é Aracaju.'),
(1, 'Qual é a capital do Tocantins?',           'A capital do Tocantins é Palmas.');
